# Generated by Django 6.1 on 2026-08-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='people_affected',
            field=models.IntegerField(default=0),
        ),
    ]
