# Generated by Django 6.1 on 2026-08-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_people_affected'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='verification_status',
            field=models.CharField(choices=[('Pending review', 'Pending review'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending review', max_length=20),
        ),
    ]
