# Generated by Django 6.1 on 2026-08-27 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_latitude_problem_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='confirmed_by',
            field=models.ManyToManyField(blank=True, related_name='confirmed_problems', to=settings.AUTH_USER_MODEL),
        ),
    ]
