# Generated by Django 6.1 on 2026-08-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_confirmed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='confirmed_by',
        ),
    ]
